# Generated by Django 5.2.7 on 2025-11-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('budget', models.CharField(blank=True, choices=[('5k-15k', '₹5,000 - ₹15,000'), ('15k-30k', '₹15,000 - ₹30,000'), ('30k-50k', '₹30,000 - ₹50,000'), ('50k+', '₹50,000+')], max_length=20, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('website', 'Website Development'), ('mobile', 'Mobile App'), ('ecommerce', 'E-commerce Store'), ('consultation', 'IT Consultation'), ('other', 'Other')], max_length=30, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
