# Generated by Django 5.2.7 on 2025-11-13 13:17

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_level', models.CharField(choices=[('FRESHER', 'Fresher'), ('EXPERIENCED', 'Experienced'), ('ALL', 'All Levels')], default='ALL', max_length=20)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('requirements', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Requirements')),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
