# Generated by Django 5.2.7 on 2025-10-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_problems_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
