# Generated by Django 5.2.7 on 2025-10-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_problems_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
